name: Feature Request
description: File a feature request
title: "[Req]: "
labels: ["feature request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: feature
    attributes:
      label: Explain the proposed feature
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Explain the possible use cases for the feature
    validations:
      required: false
  - type: textarea
    id: other
    attributes:
      label: Any other details you would like to provide?
    validations:
      required: false
